### PR TITLE
Improvements on Tantalum footprints

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR is a complete rework of the Tantalum capacitor footprints.

Footprints have all been generated by script available here:

https://github.com/SchrodingersGat/kicad-footprint-generator/blob/master/scripts/Capacitors/tantalums.py

References:

http://www.dialelectrolux.ru/files/file/Kemet/f3102.pdf

https://en.wikipedia.org/wiki/Tantalum_capacitor#Chip_capacitors_.28case_size.29

The new footprints offer the following improvements:
- Consistency (all footprints are oriented correctly, have the same polarity indication, etc)
- Silkscreen improvements (indicates polarity, and completely removed from pads
- Package outline marked on F.Fab layer
- Consistent courtyard
- Options for hand soldering, reflow soldering, wave soldering
- Addresses currently open issues https://github.com/KiCad/Capacitors_Tantalum_SMD.pretty/issues/7 and https://github.com/KiCad/Capacitors_Tantalum_SMD.pretty/issues/6

Currently all these parts fail KLC 10.7 as the references to the 3D models are improper.

I will shortly provide better 3D models for these capacitors which are parametrically generated, correctly named, and provide .wrl/.step pair instead of .wrl/.wings options. These will be submitted to the kicad-library repository as that is where the models are stored.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Examples:

tant_case

**Comment by eldarkg** [comment]
@SchrodingersGat Maybe need apply to IPC-7351 (Figure 16-1 Zero Component Rotations for Common Package Outlines) relative silkscreen (to draw 1 pin with circle)?

**Comment by SchrodingersGat** [comment]
eg

Improvements to polarization marks have been made.

**Comment by eldarkg** [comment]
@SchrodingersGat Why don't to draw the key pin like in IPC, like this?
lt

**Comment by mrnuke** [comment]
One thing to note is that this changed the footprint names and 3D shape names, so the existing wrl files will not be rendered in the 3D viewer. However, there is no associated rename of 3d files in 3dpackages/

Ex: TantalC_SizeA_EIA-3216_Reflow.wrl -> Tantalum_Case-A_EIA-3216-18.wrl

**Comment by mrnuke** [comment]
I've ordered a board to be manufactured from OSHpark with a few of the new footprints. From the 3D rendering, it seems that the indicators will show up fine. Will update this when the PCBs arrive.

tantal_test_board

**Comment by SchrodingersGat** [comment]
Great work :) I look forward to the results of your experiment

**Comment by SchrodingersGat** [comment]
@eldarkg they have been updated to match 7351-C

http://cskl.de/fileadmin/downloads/PCBLIBRARIES/Documentation/What-is-New-in-IPC-7351C_.pdf

**Comment by eldarkg** [comment]
@SchrodingersGat I don't see in this document your styles of FP.

**Comment by eldarkg** [comment]
@SchrodingersGat Can you attach the last view of changed footprints?

**Comment by SchrodingersGat** [comment]
e.g.

tant

**Comment by eldarkg** [comment]
@SchrodingersGat  I'm embarrassed with ears of FP :)

**Comment by SchrodingersGat** [comment]
ugh, they were supposed to be removed when I updated the script to be IPC compatible.. Hang on...

**Comment by SchrodingersGat** [comment]
Ears? What ears?

tant

**Comment by eldarkg** [comment]
@SchrodingersGat Hhhh. That is good :)

**Comment by mrnuke** [comment]
The commit message "Went all Mike Tyson and removed some ears" is technically incorrect. The commit removed **all** ears from the footprints, which is inconsistent with the Mike Tyson method, which only removed part of one ear.

**Comment by SchrodingersGat** [comment]
Mike Tyson is an amateur.

**Comment by mrnuke** [comment]
These are the results with git commit b54df77
Unfortunately, I do not have manufacturing examples from more recent commits.

tanty_mfg
tanty_mfg_scan

**Comment by SchrodingersGat** [comment]
@CarlPoirier these Tant packages have been updated to IPC marking guidelines also.

**Comment by SchrodingersGat** [comment]
bump

**Comment by mrnuke** [comment]
I find the updated footprints to be a welcome improvement over the old style.

**Comment by pointhi** [comment]
some dimensions differ between name and definition: https://github.com/SchrodingersGat/kicad-footprint-generator/blob/master/scripts/Capacitors/tantalums.py#L35

is this intended?

**Comment by SchrodingersGat** [comment]
untitled

@pointhi  as far as I can tell it matches the datasheet. Is there a particular dimension that irks you?

**Comment by pointhi** [comment]
ok, i though the name represents the metric size

**Comment by SchrodingersGat** [comment]
Any other issues with this one then? :)

**Comment by pointhi** [comment]
why do you use the specific dimesions of a single manufactur instead of the general ones listed on wikipedia?

**Comment by SchrodingersGat** [comment]
It looks like the only differences are the package heights? Unless you can spot other differences? 

Should I  add _Kemet_ to the name for these parts?

**Comment by SchrodingersGat** [comment]
@jkriege2 want to check this one out when you have time? :)

**Comment by jkriege2** [comment]
Hi!

@pointhi  @CarlPoirier @diggit : this PR looks good to me ... should we merge?


JAN

**Comment by jkriege2** [comment]
Since nobody seems to have any objections ... and I also don't see any and like the PR: I'll merge ;-)

Nice work,
JAN

**Pull request merged**
