### PR TITLE
Create D9.kicad_mod

### PR DESCRIPTION
**Pull request by savenlid**
Murata D9 size,
It actually varies quite a lot from kicad default 7343
also this once contains assembly drawing with polarity marking,
and that is important.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @savenlid can you link me to a datasheet for this particular cap? 

I agree that assembly drawings and polarity markings are important - the other footprints have all been updated, just waiting on the PR to be accepted https://github.com/KiCad/Capacitors_Tantalum_SMD.pretty/pull/8

**Comment by evanshultz** [comment]
@savenlid Can you please let us know which component you're referring to?

@SchrodingersGat My suspicion is that the "D9" is referring to the package on [page 4 of this datasheet](http://www.murata.com/~/media/webrenewal/support/library/catalog/products/capacitor/polymer/c90e.ashx). If so, I believe the current 7343-43 footprint will fit this capacitor nicely. Please take a look. (That being said, we don't have anything to exactly fit D6 but I think 7343-43 will be fine here as well.)

**Comment by savenlid** [comment]
It depends on your modus operandi

This is my way

In this case i think the case is a panasonic poscap
Assume  I want to use this specific part.

1: I look into the datasheet for footprint and creates it.
2: I match a 3D model to the footprint

I could have started looking around various libraries and see if I could
guestimate another footprint that would somewhat match the D9 footprint.
I could do that, but I will never do that.
Not me.

Its quicker for me to create the actual footprint wanted by manufacturers
datasheet , pair the correct 3D model (heightm and looks) and be done with
it.

Should this footprint in the future for any reason need tuning, like
smaller courtyard, better 3D or modified geometry, it will only affect this
manufactures parts.

This is my structure
Footprints/Panasonic/3D
Panasonic will keep the *,mod files for panasonic parts
3D will keep the step files for the above.

just explaining why looking for random footprints to match is not an option
for me.

Best Regards
/Nicholas


2017-06-21 22:02 GMT+02:00 evanshultz <notifications@github.com>:

**Comment by Shackmeister** [comment]
@evanshultz @savenlid should this one also be closed?

**Pull request closed without merging**
